name: GuestUnlock
main: se.myller.GuestUnlock.Main
version: 1.8.6
description: >
             This plugin is used to send a message to admins when a player types the correct password.
commands:
  gutest:
    description: Test, aka ping-command
    usage: /<command>
  guestunlock:
    description: Sends password to admins
    usage: /<command> [Password]
  gupassword:
    description: Changes the correct password
    usage: /<command> [New Password]

permissions:
  GuestUnlock.guest:
    description: Seen as a Guest
    default: false
  GuestUnlock.moderator:
    description: See message when someone sends the correct password
    default: false
  GuestUnlock.admin:
    description: Change the password
    default: op
    children:
      GuestUnlock.moderator: true